### ISSUE TITLE
No Cleanup after `storage.backup.max_age`

### ISSUE THREAD

**Issue by tassilogroeper** [wearewondrous/psh-toolbelt#7]
Intentionally the backups on the remote storage should be deleted after the defined amount of time `storage.backup.max_age`. Currently this is not working.

## Background info
In order to allow different storage services in the future (gdrive, aws, ...) the datetime is encoded in the foldername as `date("c")`and compared from there.

Find out why and fix it.

**Comment by rainer-friederich** [comment]
new release created, lets have a look
